### ISSUE TITLE
Pulling the latest pip and virtualenv

### ISSUE THREAD

**Issue by just-be-dev** [Ehlster/node-python-virtualenv#1]
The way this project is currently setup, aren't PIP and virtualenv way out of date? Is it possible to have those libraries automatically pulled from github instead of requiring using a submodule?

Perhaps just pulling down the latest get-pip.py file and virtualenv directory. 

Thoughts?

**Comment by just-be-dev** [comment]
You could perhaps do two things:
1. Download git-pip.py directly from pip's repo using node's http module
2. Directly clone virtualenv using something like [nodegit](https://github.com/nodegit/nodegit) or download it in some other way.

**Comment by Ehlster** [comment]
I do agree that PIP and virtualenv are way out of date in this project. Therefore, some background on the project: It was some kind of a little hack I wrote in one evening after hours to smuggle in python in a project that should be done with node.js ;-). Since then I left the company (and web development and concentrated on mobile development), so this project was not maintained a lot. Actually I am surprised that you found and used it, but it makes me happy that someone can make use of it.

While I agree that the versions are out of date, there are some disadvantages in always getting the latest version. At the moment, the used version is tested and it works. I don't think that it is a good idea to always use the latest version of a dependency without running some tests. At least there should be some checks if anything breaks.

Thoughts?

(But this discussion may be a little bit late since you already opened a merge request for the changes.)

**Comment by just-be-dev** [comment]
Heh, well, I'm trying to do an unholy hybrid myself. I'm wanting to integrate [robotframework](https://github.com/robotframework/robotframework) with [atom](https://github.com/atom/atom), and this is one very, very useful tool to help me down that road. 

That's true. I know with pip, they fix errors all the time that cause users headaches. It would be nice to have the latest working version, but it's non-trivial in figuring out what that is. One option would be to provide a configuration option to let the user specify which version of pip and virtualenv to grab.
